// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMQmONOpiYg6myHYCPf1BMwgOYnJKQi-U',
    appId: '1:800194676841:web:3dbe81c78a771f97bbfaf8',
    messagingSenderId: '800194676841',
    projectId: 'aplikasi-gym-ft-umj',
    authDomain: 'aplikasi-gym-ft-umj.firebaseapp.com',
    databaseURL: 'https://aplikasi-gym-ft-umj-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-gym-ft-umj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvxKVQFo4BK6wZieNnevxL_ye_UaOOM0I',
    appId: '1:800194676841:android:848cbdfc58a6487ebbfaf8',
    messagingSenderId: '800194676841',
    projectId: 'aplikasi-gym-ft-umj',
    databaseURL: 'https://aplikasi-gym-ft-umj-default-rtdb.firebaseio.com',
    storageBucket: 'aplikasi-gym-ft-umj.firebasestorage.app',
  );

}